namespace: cmms

backend:
  image:
    repository: ghcr.io/georgeargyris/cmms-backend
    tag: v1.0.0
    pullPolicy: IfNotPresent
  replicas: 2
  port: 3000
  dbHost: postgres-service

frontend:
  image:
    repository: ghcr.io/georgeargyris/cmms-frontend
    tag: v1.0.0
    pullPolicy: IfNotPresent
  replicas: 2
  port: 80
  nodePort: 30081

postgres:
  image:
    repository: postgres
    tag: 15-alpine
  port: 5432
  storage: 2Gi
  persistence:
    enabled: true
    size: 2Gi

service:
  backendNodePort: 30300
  frontendNodePort: 30081

secret:
  postgresDb: cmmsdb
  postgresUser: cmmsuser
  postgresPassword: dummy-secret-replace-with-set
  jwtSecret: dummy-secret-replace-with-set