apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB:       {{ .Values.secret.postgresDb }}
  POSTGRES_USER:     {{ .Values.secret.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword }}
  JWT_SECRET:        {{ .Values.secret.jwtSecret }}